---
title: "Schedule"
format: 
  html:
    css: schedule.css
editor: visual
---

+---------+--------------+---------------------------------------------------------------------------------+------------------------------------------+---------------------------------------------------------------------------------------------+-------------------------------------------------+---------------------------------------------------------------------------------+
| Wk      |              | Mon                                                                             | Tue                                      | Wed                                                                                         | Thu                                             | Fri                                                                             |
+=========+==============+=================================================================================+==========================================+=============================================================================================+=================================================+=================================================================================+
| 1       | Jan 12-15    | [Welcome]{.lecture}                                                             | [Lab 1]{.lab}                            | [Lecture 2]{.lab}                                                                           | [Lab 2]{.lab}                                   | Lecture 2 continued                                                             |
|         |              |                                                                                 |                                          |                                                                                             |                                                 |                                                                                 |
|         |              | Syllabus                                                                        | Introduction to R and RStudio            | [Data and Variables](../lectures/slides/lecture-02-data-and-variables)                      | Importing Data                                  |                                                                                 |
|         |              |                                                                                 |                                          |                                                                                             |                                                 |                                                                                 |
|         |              | [Lecture 1]{.lecture}                                                           |                                          |                                                                                             |                                                 |                                                                                 |
|         |              |                                                                                 |                                          |                                                                                             |                                                 |                                                                                 |
|         |              | [Statistics and Samples](../lectures/slides/lecture-01-statistics-samples)      |                                          |                                                                                             |                                                 |                                                                                 |
+---------+--------------+---------------------------------------------------------------------------------+------------------------------------------+---------------------------------------------------------------------------------------------+-------------------------------------------------+---------------------------------------------------------------------------------+
| 2       | Jan 19-23    | [No Class]{.noclass}                                                            | [Lab 3]{.lab}                            | [Lecture 3]{.lab}                                                                           | [Lab 4]{.lab}                                   | [Lecture 4]{.lecture}                                                           |
|         |              |                                                                                 |                                          |                                                                                             |                                                 |                                                                                 |
|         |              | *Martin Luther King Holiday*                                                    | [Importing Data](../labs/importing-data) | [Effective data visualization](../lectures/slides/lecture-03-effective-data-visualization/) | [Graphing with ggplot](../labs/graphing-ggplot) | [Visualizing data types](../lectures/slides/lecture-04-visualizing-data-types/) |
+---------+--------------+---------------------------------------------------------------------------------+------------------------------------------+---------------------------------------------------------------------------------------------+-------------------------------------------------+---------------------------------------------------------------------------------+
| 3       | Jan 26-30    | [Lecture 4]{.lecture}                                                           | [Lab 5]{.lab}                            | [Lecture 5]{.lab}                                                                           | [Lab 6]{.lab}                                   | [Lecture 5]{.lab}                                                               |
|         |              |                                                                                 |                                          |                                                                                             |                                                 |                                                                                 |
|         |              | [Visualizing data types](../lectures/slides/lecture-04-visualizing-data-types/) | Graphing Distributions                   | Describing Data                                                                             | Descriptive statistics                          | continued.                                                                      |
+---------+--------------+---------------------------------------------------------------------------------+------------------------------------------+---------------------------------------------------------------------------------------------+-------------------------------------------------+---------------------------------------------------------------------------------+
| 4       | Feb 2-6      | [Lecture 6]{.lab}                                                               | [Lab 7]{.lab}                            | [Lecture 7]{.lab}                                                                           | [EDA Project]{.lab}                             | [Exam 1]{.exam}                                                                 |
|         |              |                                                                                 |                                          |                                                                                             |                                                 |                                                                                 |
|         |              | Estimating with uncertainty                                                     | Estimating with uncertainty              | Probability                                                                                 | Choose question                                 | Lectures 1-7                                                                    |
|         |              |                                                                                 |                                          |                                                                                             |                                                 |                                                                                 |
|         |              |                                                                                 |                                          |                                                                                             | Find datasets                                   | ABD Chapters 1-5                                                                |
+---------+--------------+---------------------------------------------------------------------------------+------------------------------------------+---------------------------------------------------------------------------------------------+-------------------------------------------------+---------------------------------------------------------------------------------+
| 5       | Feb 9-14     | [Lecture]{.lab}                                                                 | Lab 8                                    | [Lecture]{.lab}                                                                             |                                                 | [Lecture]{.lab}                                                                 |
|         |              |                                                                                 |                                          |                                                                                             |                                                 |                                                                                 |
|         |              | Hypothesis testing                                                              | Data subsetting                          |                                                                                             |                                                 |                                                                                 |
+---------+--------------+---------------------------------------------------------------------------------+------------------------------------------+---------------------------------------------------------------------------------------------+-------------------------------------------------+---------------------------------------------------------------------------------+
| 6       | Feb 16-20    |                                                                                 |                                          |                                                                                             |                                                 |                                                                                 |
+---------+--------------+---------------------------------------------------------------------------------+------------------------------------------+---------------------------------------------------------------------------------------------+-------------------------------------------------+---------------------------------------------------------------------------------+
| 7       | Feb 23-27    |                                                                                 |                                          |                                                                                             |                                                 |                                                                                 |
+---------+--------------+---------------------------------------------------------------------------------+------------------------------------------+---------------------------------------------------------------------------------------------+-------------------------------------------------+---------------------------------------------------------------------------------+
| 8       | Mar 2-6      |                                                                                 |                                          |                                                                                             |                                                 |                                                                                 |
+---------+--------------+---------------------------------------------------------------------------------+------------------------------------------+---------------------------------------------------------------------------------------------+-------------------------------------------------+---------------------------------------------------------------------------------+
|         | Mar 9-13     |                                                                                 |                                          |                                                                                             |                                                 |                                                                                 |
+---------+--------------+---------------------------------------------------------------------------------+------------------------------------------+---------------------------------------------------------------------------------------------+-------------------------------------------------+---------------------------------------------------------------------------------+
| 9       | Mar 16-20    |                                                                                 |                                          |                                                                                             |                                                 |                                                                                 |
+---------+--------------+---------------------------------------------------------------------------------+------------------------------------------+---------------------------------------------------------------------------------------------+-------------------------------------------------+---------------------------------------------------------------------------------+
| 10      | Mar 23-27    |                                                                                 |                                          |                                                                                             |                                                 |                                                                                 |
+---------+--------------+---------------------------------------------------------------------------------+------------------------------------------+---------------------------------------------------------------------------------------------+-------------------------------------------------+---------------------------------------------------------------------------------+
| 11      | Mar 30-Apr 3 |                                                                                 |                                          |                                                                                             |                                                 |                                                                                 |
+---------+--------------+---------------------------------------------------------------------------------+------------------------------------------+---------------------------------------------------------------------------------------------+-------------------------------------------------+---------------------------------------------------------------------------------+
| 12      | Apr 6-10     |                                                                                 |                                          |                                                                                             |                                                 |                                                                                 |
+---------+--------------+---------------------------------------------------------------------------------+------------------------------------------+---------------------------------------------------------------------------------------------+-------------------------------------------------+---------------------------------------------------------------------------------+
| 13      | Apr 13-17    |                                                                                 |                                          |                                                                                             |                                                 |                                                                                 |
+---------+--------------+---------------------------------------------------------------------------------+------------------------------------------+---------------------------------------------------------------------------------------------+-------------------------------------------------+---------------------------------------------------------------------------------+
| 14      | Apr 20-24    |                                                                                 | [Student Academic Conference]{.exam}     |                                                                                             |                                                 |                                                                                 |
+---------+--------------+---------------------------------------------------------------------------------+------------------------------------------+---------------------------------------------------------------------------------------------+-------------------------------------------------+---------------------------------------------------------------------------------+
| 15      | Apr 27-May 1 |                                                                                 |                                          |                                                                                             |                                                 |                                                                                 |
+---------+--------------+---------------------------------------------------------------------------------+------------------------------------------+---------------------------------------------------------------------------------------------+-------------------------------------------------+---------------------------------------------------------------------------------+
| 16      | May 4-8      | Final Exam Review                                                               | [Final Exam]{.exam}                      |                                                                                             |                                                 |                                                                                 |
|         |              |                                                                                 |                                          |                                                                                             |                                                 |                                                                                 |
|         |              |                                                                                 | Tuesday, May 5\                          |                                                                                             |                                                 |                                                                                 |
|         |              |                                                                                 | 7:30-9:30 AM\                            |                                                                                             |                                                 |                                                                                 |
|         |              |                                                                                 | Langseth 104                             |                                                                                             |                                                 |                                                                                 |
+---------+--------------+---------------------------------------------------------------------------------+------------------------------------------+---------------------------------------------------------------------------------------------+-------------------------------------------------+---------------------------------------------------------------------------------+
