---
title: "Schedule"
format: 
  html:
    css: schedule.css
editor: visual
---

+---------+--------------+---------------------------------------------------------------------------------+------------------------------------------------------------------------+---------------------------------------------------------------------------------------------+-------------------------------------------------------------------+---------------------------------------------------------------------------------+
| Wk      | Dates        | Mon                                                                             | Tue                                                                    | Wed                                                                                         | Thu                                                               | Fri                                                                             |
+=========+==============+=================================================================================+========================================================================+=============================================================================================+===================================================================+=================================================================================+
| 1       | Jan 12-15    | [Welcome]{.lecture}                                                             | [Lab 1]{.lab}                                                          | [Lecture 2]{.lab}                                                                           | [Lab 2]{.lab}                                                     | [Lecture 2]{.lecture}                                                           |
|         |              |                                                                                 |                                                                        |                                                                                             |                                                                   |                                                                                 |
|         |              | Syllabus                                                                        | [Introduction to R and RStudio](../labs/introduction-to-r-and-rstudio) | [Data and Variables](../lectures/slides/lecture-02-data-and-variables)                      | [Workflow and Data Types](../labs/workflow-and-data-types)        | continued                                                                       |
|         |              |                                                                                 |                                                                        |                                                                                             |                                                                   |                                                                                 |
|         |              | [Lecture 1]{.lecture}                                                           |                                                                        |                                                                                             |                                                                   |                                                                                 |
|         |              |                                                                                 |                                                                        |                                                                                             |                                                                   |                                                                                 |
|         |              | [Statistics and Samples](../lectures/slides/lecture-01-statistics-samples)      |                                                                        |                                                                                             |                                                                   |                                                                                 |
+---------+--------------+---------------------------------------------------------------------------------+------------------------------------------------------------------------+---------------------------------------------------------------------------------------------+-------------------------------------------------------------------+---------------------------------------------------------------------------------+
| 2       | Jan 19-23    | [No Class]{.noclass}                                                            | [Lab 3]{.lab}                                                          | [Lecture 3]{.lab}                                                                           | [Lab 4]{.lab}                                                     | [Lecture 4]{.lecture}                                                           |
|         |              |                                                                                 |                                                                        |                                                                                             |                                                                   |                                                                                 |
|         |              | *Martin Luther King Holiday*                                                    | [Importing Data](../labs/importing-data)                               | [Effective data visualization](../lectures/slides/lecture-03-effective-data-visualization/) | [Graphing with ggplot](../labs/graphing-ggplot)                   | [Visualizing data types](../lectures/slides/lecture-04-visualizing-data-types/) |
|         |              |                                                                                 |                                                                        |                                                                                             |                                                                   |                                                                                 |
|         |              |                                                                                 |                                                                        |                                                                                             |                                                                   | ::: {.alert .alert-info}                                                        |
|         |              |                                                                                 |                                                                        |                                                                                             |                                                                   | **Update.** Class was cancelled due to weather.                                 |
|         |              |                                                                                 |                                                                        |                                                                                             |                                                                   | :::                                                                             |
+---------+--------------+---------------------------------------------------------------------------------+------------------------------------------------------------------------+---------------------------------------------------------------------------------------------+-------------------------------------------------------------------+---------------------------------------------------------------------------------+
| 3       | Jan 26-30    | [Lecture 4]{.lecture}                                                           | [Lab 5]{.lab}                                                          | [Lecture 5]{.lab}                                                                           | [Project]{.lab}                                                   | [Lecture 5]{.lab}                                                               |
|         |              |                                                                                 |                                                                        |                                                                                             |                                                                   |                                                                                 |
|         |              | [Visualizing data types](../lectures/slides/lecture-04-visualizing-data-types/) | [ggplot2 Visualization Challenge](../labs/ggplot2-vis-challenge)       | [Describing Data](../lectures/slides/lecture-05-describing-data/)                           | Activity: [Introduction to the EDA Project](../project/index.qmd) | continued.                                                                      |
+---------+--------------+---------------------------------------------------------------------------------+------------------------------------------------------------------------+---------------------------------------------------------------------------------------------+-------------------------------------------------------------------+---------------------------------------------------------------------------------+
| 4       | Feb 2-6      | [Lecture 6]{.lab}                                                               | [Project]{.lab}                                                        | [Lecture 7]{.lab}                                                                           | [Lab 6]{.lab}                                                     | [Lecture 7]{.lab}                                                               |
|         |              |                                                                                 |                                                                        |                                                                                             |                                                                   |                                                                                 |
|         |              | [Estimating with uncertainty](../lectures/slides/lecture-06-uncertainty/)       | ::: {.alert .alert-warning}                                            | [Probability](../lectures/slides/lecture-07-probability/)                                   | Estimating means with uncertainty                                 | continued.                                                                      |
|         |              |                                                                                 | **Due on D2L.**                                                        |                                                                                             |                                                                   |                                                                                 |
|         |              |                                                                                 |                                                                        |                                                                                             |                                                                   |                                                                                 |
|         |              |                                                                                 | [Team Formation](../project/team-formation.qmd)                        |                                                                                             |                                                                   |                                                                                 |
|         |              |                                                                                 | :::                                                                    |                                                                                             |                                                                   |                                                                                 |
+---------+--------------+---------------------------------------------------------------------------------+------------------------------------------------------------------------+---------------------------------------------------------------------------------------------+-------------------------------------------------------------------+---------------------------------------------------------------------------------+
| 5       | Feb 9-14     | [Exam 1]{.exam}                                                                 | [Lab 8]{.lab}                                                          | [Lecture 8]{.lab}                                                                           | [Lab 9]{.lab}                                                     | [Lecture 9]{.lab}                                                               |
|         |              |                                                                                 |                                                                        |                                                                                             |                                                                   |                                                                                 |
|         |              | Lectures 1-7                                                                    | Data subsetting                                                        | Hypothesis testing                                                                          | ::: {.alert .alert-warning}                                       |                                                                                 |
|         |              |                                                                                 |                                                                        |                                                                                             | **Due on D2L.** Project Data Readiness Check                      |                                                                                 |
|         |              | ABD Chapters 1-5                                                                |                                                                        |                                                                                             | :::                                                               |                                                                                 |
+---------+--------------+---------------------------------------------------------------------------------+------------------------------------------------------------------------+---------------------------------------------------------------------------------------------+-------------------------------------------------------------------+---------------------------------------------------------------------------------+
| 6       | Feb 16-20    | [No Class]{.noclass}                                                            | [Lab]{.lab}                                                            | [Lecture 10]{.lab}                                                                          | [Lab]{.lab}                                                       | [Lecture 11]{.lab}                                                              |
|         |              |                                                                                 |                                                                        |                                                                                             |                                                                   |                                                                                 |
|         |              | Non-instructional Day                                                           |                                                                        |                                                                                             | ::: {.alert .alert-warning}                                       |                                                                                 |
|         |              |                                                                                 |                                                                        |                                                                                             | **Due on D2L.** Project Abstract Draft 1                          |                                                                                 |
|         |              |                                                                                 |                                                                        |                                                                                             | :::                                                               |                                                                                 |
+---------+--------------+---------------------------------------------------------------------------------+------------------------------------------------------------------------+---------------------------------------------------------------------------------------------+-------------------------------------------------------------------+---------------------------------------------------------------------------------+
| 7       | Feb 23-27    | [Lecture 12]{.lab}                                                              | [Lab]{.lab}                                                            | [No Class]{.noclass}                                                                        | [Lab]{.lab}                                                       | [Lecture 13]{.lab}                                                              |
|         |              |                                                                                 |                                                                        |                                                                                             |                                                                   |                                                                                 |
|         |              |                                                                                 |                                                                        | See D2L for homework assignment                                                             |                                                                   |                                                                                 |
+---------+--------------+---------------------------------------------------------------------------------+------------------------------------------------------------------------+---------------------------------------------------------------------------------------------+-------------------------------------------------------------------+---------------------------------------------------------------------------------+
| 8       | Mar 2-6      | [Exam 2]{.exam}                                                                 | [Lab]{.lab}                                                            | [Lecture 14]{.lab}                                                                          | [Lab]{.lab}                                                       | [Lecture]{.lab}15                                                               |
|         |              |                                                                                 |                                                                        |                                                                                             |                                                                   |                                                                                 |
|         |              | Lectures 8-13                                                                   |                                                                        |                                                                                             | ::: {.alert .alert-warning}                                       |                                                                                 |
|         |              |                                                                                 |                                                                        |                                                                                             | **Due on D2L.** Project Abstract Draft 2                          |                                                                                 |
|         |              | ABD Chapters 10-                                                                |                                                                        |                                                                                             | :::                                                               |                                                                                 |
+---------+--------------+---------------------------------------------------------------------------------+------------------------------------------------------------------------+---------------------------------------------------------------------------------------------+-------------------------------------------------------------------+---------------------------------------------------------------------------------+
|         | Mar 9-13     | [No Class]{.noclass}                                                            | [No Class]{.noclass}                                                   | [No Class]{.noclass}                                                                        | [No Class]{.noclass}                                              | [No Class]{.noclass}                                                            |
|         |              |                                                                                 |                                                                        |                                                                                             |                                                                   |                                                                                 |
|         |              | *Spring break*                                                                  | *Spring break*                                                         | *Spring break*                                                                              | *Spring break*                                                    | *Spring break*                                                                  |
+---------+--------------+---------------------------------------------------------------------------------+------------------------------------------------------------------------+---------------------------------------------------------------------------------------------+-------------------------------------------------------------------+---------------------------------------------------------------------------------+
| 9       | Mar 16-20    | [Lecture 16]{.lab}                                                              | [Lab]{.lab}                                                            | [Lecture 17]{.lab}                                                                          | [Lab]{.lab}                                                       | [Lecture 18]{.lab}                                                              |
|         |              |                                                                                 |                                                                        |                                                                                             |                                                                   |                                                                                 |
|         |              |                                                                                 | Activity TBD                                                           | ::: {.alert .alert-warning}                                                                 | Activity TBD                                                      |                                                                                 |
|         |              |                                                                                 |                                                                        | **Deadline.**                                                                               |                                                                   |                                                                                 |
|         |              |                                                                                 | ::: {.alert .alert-warning}                                            |                                                                                             |                                                                   |                                                                                 |
|         |              |                                                                                 | **Deadline.** SAC application deadline for BIOL 275 students           | General SAC Application Deadline                                                            |                                                                   |                                                                                 |
|         |              |                                                                                 | :::                                                                    | :::                                                                                         |                                                                   |                                                                                 |
+---------+--------------+---------------------------------------------------------------------------------+------------------------------------------------------------------------+---------------------------------------------------------------------------------------------+-------------------------------------------------------------------+---------------------------------------------------------------------------------+
| 10      | Mar 23-27    | [Lecture 19]{.lab}                                                              | [Lab]{.lab}                                                            | [Lecture 20]{.lab}                                                                          | [Project]{.lab}                                                   | [Lecture 21]{.lab}                                                              |
|         |              |                                                                                 |                                                                        |                                                                                             |                                                                   |                                                                                 |
|         |              |                                                                                 |                                                                        |                                                                                             | Draft Data Analysis Check-In                                      |                                                                                 |
+---------+--------------+---------------------------------------------------------------------------------+------------------------------------------------------------------------+---------------------------------------------------------------------------------------------+-------------------------------------------------------------------+---------------------------------------------------------------------------------+
| 11      | Mar 30-Apr 3 | [Lecture 22]{.lab}                                                              | [Lab]{.lab}                                                            | [Lecture 23]{.lab}                                                                          | [Project]{.lab}                                                   | [Exam 3]{.exam}                                                                 |
|         |              |                                                                                 |                                                                        |                                                                                             |                                                                   |                                                                                 |
|         |              |                                                                                 |                                                                        | ::: {.alert .alert-warning}                                                                 | Activity: Project Analysis Check-In                               | Lectures 14-21                                                                  |
|         |              |                                                                                 |                                                                        | **Due on D2L.** Project Check-In Report.                                                    |                                                                   |                                                                                 |
|         |              |                                                                                 |                                                                        | :::                                                                                         |                                                                   | ABD Chapters 10-                                                                |
+---------+--------------+---------------------------------------------------------------------------------+------------------------------------------------------------------------+---------------------------------------------------------------------------------------------+-------------------------------------------------------------------+---------------------------------------------------------------------------------+
| 12      | Apr 6-10     | [No Class]{.noclass}                                                            | [Lab]{.lab}                                                            | [Lecture]{.lab} 24                                                                          | [Lab]{.lab}                                                       | [Lecture 25]{.lab}                                                              |
|         |              |                                                                                 |                                                                        |                                                                                             |                                                                   |                                                                                 |
|         |              | See D2L for homework assignment                                                 |                                                                        |                                                                                             | ::: {.alert .alert-warning}                                       |                                                                                 |
|         |              |                                                                                 |                                                                        |                                                                                             | **Due on D2L.** Project Poster Draft 1.                           |                                                                                 |
|         |              |                                                                                 |                                                                        |                                                                                             | :::                                                               |                                                                                 |
+---------+--------------+---------------------------------------------------------------------------------+------------------------------------------------------------------------+---------------------------------------------------------------------------------------------+-------------------------------------------------------------------+---------------------------------------------------------------------------------+
| 13      | Apr 13-17    | [Lecture 26]{.lab}                                                              | [Lab]{.lab}                                                            | [Lecture 27]{.lab}                                                                          | [Lab]{.lab}                                                       | [Lecture]{.lab}28                                                               |
|         |              |                                                                                 |                                                                        |                                                                                             |                                                                   |                                                                                 |
|         |              |                                                                                 |                                                                        |                                                                                             | ::: {.alert .alert-warning}                                       |                                                                                 |
|         |              |                                                                                 |                                                                        |                                                                                             | **Due on D2L.** Project Poster Final Version.                     |                                                                                 |
|         |              |                                                                                 |                                                                        |                                                                                             | :::                                                               |                                                                                 |
+---------+--------------+---------------------------------------------------------------------------------+------------------------------------------------------------------------+---------------------------------------------------------------------------------------------+-------------------------------------------------------------------+---------------------------------------------------------------------------------+
| 14      | Apr 20-24    | [Lecture 29]{.lab}                                                              | [Student Academic Conference]{.exam}                                   | [Lecture 30]{.lab}                                                                          | [Lab]{.lab}                                                       | [Lecture 31]{.lab}                                                              |
+---------+--------------+---------------------------------------------------------------------------------+------------------------------------------------------------------------+---------------------------------------------------------------------------------------------+-------------------------------------------------------------------+---------------------------------------------------------------------------------+
| 15      | Apr 27-May 1 | [Lecture]{.lab}32                                                               | [Lab]{.lab}                                                            | [Lecture 33]{.lab}                                                                          | [Lab]{.lab}                                                       | [Lecture 34]{.lab}                                                              |
+---------+--------------+---------------------------------------------------------------------------------+------------------------------------------------------------------------+---------------------------------------------------------------------------------------------+-------------------------------------------------------------------+---------------------------------------------------------------------------------+
| 16      | May 4-8      | [Review]{.exam}                                                                 | [Final Exam]{.exam}                                                    | [No Class]{.noclass}                                                                        | [No Class]{.noclass}                                              | [No Class]{.noclass}                                                            |
|         |              |                                                                                 |                                                                        |                                                                                             |                                                                   |                                                                                 |
|         |              | Final Exam Review                                                               | Tuesday, May 5\                                                        | Final Exam Week                                                                             | Final Exam Week                                                   | Final Exam Week                                                                 |
|         |              |                                                                                 | 7:30-9:30 AM\                                                          |                                                                                             |                                                                   |                                                                                 |
|         |              |                                                                                 | Langseth 104                                                           |                                                                                             |                                                                   |                                                                                 |
+---------+--------------+---------------------------------------------------------------------------------+------------------------------------------------------------------------+---------------------------------------------------------------------------------------------+-------------------------------------------------------------------+---------------------------------------------------------------------------------+
