{
  "hash": "855e60f9359903fe9ee4cbf0d1afaf8f",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Lab 6: Describing Data with Summary Statistics\"\ndescription: \"Using descriptive statistics and graphs to summarize, compare, and interpret biological data.\"\nformat: html\nexecute:\n  echo: true\n---\n\n## Learning Objectives\n\nBy the end of this lab, students will be able to:\n\n-   Explain how measures of center (mean, median) and spread (SD, SE) summarize different aspects of a distribution\n-   Explain how mean and median differ in skewed distributions and describe how each summarizes the data\n-   Create and interpret summary tables of grouped data using descriptive statistics\n-   Explain the difference between SD and SE in words, and describe what each does and does *not* represent\n-   Use the 2SE rule of thumb to describe uncertainty in group means, without making inferential claims\n-   Interpret different graph types used to address distributional versus mean-based questions\n-   Describe patterns in data clearly using both figures and concise Results-style text\n\n## Getting started\n\nBefore you begin the lab activities, complete the following steps to make sure you are fully set up.\n\n1.  **Get the Lab Worksheet.**\n\n    Pick up a physical copy of the lab worksheet, or print one if you are working outside of class.\\\n    <a href=\"lab-06-worksheet.pdf\" download class=\"btn btn-outline-primary mt-3\">Download Lab Worksheet (PDF, if needed)</a>\n\n2.  **Open Posit Cloud and Start Lab 6.**\n\n    Log in to **Posit Cloud**, navigate to **Your Workspace**, and create a new project for Lab 6 Describing Data\n\n3.  **Install required packages**\n\n    Install the required packages for this lab, including **tidyverse** and lterdatasampler using the Packages tab or by running the following code ***in the Console***:\n\n\n    ::: {.cell}\n    \n    ```{.r .cell-code}\n    install.packages(c(\"tidyverse\", \"lterdatasampler\"))\n    ```\n    :::\n\n\n4.  **Create an R Script**\n\n    Create a new R script and save it as **lab-6-script.R**\n\n5.  **Load the packages**\n\n    Copy and paste this code to your R script and run it to load the packages. Remember to run both library commands (Ctrl+Enter on one line, then the next).\n\n\n    ::: {.cell}\n    \n    ```{.r .cell-code}\n    # load packages --------------------------------------------------------------\n    \n    library(tidyverse)\n    library(lterdatasampler)\n    ```\n    :::\n\n\n::: callout-note\n## Checkpoint\n\nAt this point, you should have:\n\n-   These instructions open in a web browser.\n-   Your Lab 6 project open in Posit Cloud in another browser window.\n-   The required packages installed and loaded without errors\n-   The Lab 6 worksheet in front of you.\n\nDo not continue until all of the above steps are working correctly.\n:::\n\n## Overview\n\nIn this lab, you will practice describing data, not testing hypotheses. The goal is to learn how to summarize biological data in ways that are meaningful, interpretable, and appropriate for the question being asked.\n\nYou will work with numerical variables and use descriptive statistics—such as the mean, median, standard deviation (SD), and standard error (SE)—to describe patterns in the data. You will also use the 2SE rule of thumb as a way to describe uncertainty in estimated means, without making inferential or causal claims.\n\nA key focus of this lab is judgment. Different summaries and graphs answer different questions. Some plots are best for visualizing distributions and identifying skew or outliers, while others are best for comparing group means and their uncertainty. You will see examples of both, and you will practice choosing and interpreting them appropriately.\n\nWe will begin with a worked example using a large ecological dataset to walk through the workflow step by step. You will then apply the same ideas to a smaller dataset, creating summary statistics, visualizations, and a short Results-style description of the data. The skills you practice here will be used again in later labs and in your exploratory data analysis (EDA) project.\n\n## Worked Example: Describing Data Step by Step\n\nIn this section, we will walk through a complete example of how to describe biological data using summary statistics and graphs. The goal is not to learn new plot types, but to see how different graphs emphasize different aspects of the same data.\n\nWhile group means can be shown on many kinds of plots, some visualizations emphasize distribution shape, skew, and outliers, whereas others emphasize central tendency and uncertainty.\n\nYou will also see how plots based on summary statistics often use a much narrower y-axis scale than plots showing raw data, which can make differences in means appear large even when they are small relative to the full range of the data.\n\n### Dataset overview: `and_vertebrates`\n\nThe `and_vertebrates` dataset contains measurements of vertebrates sampled at multiple stream sections in the Andrews Experimental Forest LTER. In this lab, we will focus on **body length** as the numerical variable of interest, and use **species** and **stream section** as categorical grouping variables. These variables allow us to summarize and visualize the data across groups using descriptive statistics and graphs.\n\nFor a full description of the `and_vertebrates` dataset and the other data samples included in the **lterdatasampler** package, see the package website at **https://lterdatasampler.lter.github.io/**. If you want to look up variable names or documentation, you can also use `?and_vertebrates` after loading the package.\n\nTo start exploring the data in R, first load the dataset and then use functions like `print()` and `glimpse()` to view its structure and contents. For example:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(lterdatasampler)\n\nprint(and_vertebrates)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 32,209 × 16\n    year sitecode section reach  pass unitnum unittype vert_index pitnumber\n   <dbl> <chr>    <chr>   <chr> <dbl>   <dbl> <chr>         <dbl>     <dbl>\n 1  1987 MACKCC-L CC      L         1       1 R                 1        NA\n 2  1987 MACKCC-L CC      L         1       1 R                 2        NA\n 3  1987 MACKCC-L CC      L         1       1 R                 3        NA\n 4  1987 MACKCC-L CC      L         1       1 R                 4        NA\n 5  1987 MACKCC-L CC      L         1       1 R                 5        NA\n 6  1987 MACKCC-L CC      L         1       1 R                 6        NA\n 7  1987 MACKCC-L CC      L         1       1 R                 7        NA\n 8  1987 MACKCC-L CC      L         1       1 R                 8        NA\n 9  1987 MACKCC-L CC      L         1       1 R                 9        NA\n10  1987 MACKCC-L CC      L         1       1 R                10        NA\n# ℹ 32,199 more rows\n# ℹ 7 more variables: species <chr>, length_1_mm <dbl>, length_2_mm <dbl>,\n#   weight_g <dbl>, clip <chr>, sampledate <date>, notes <chr>\n```\n\n\n:::\n\n```{.r .cell-code}\nglimpse(and_vertebrates)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 32,209\nColumns: 16\n$ year        <dbl> 1987, 1987, 1987, 1987, 1987, 1987, 1987, 1987, 1987, 1987…\n$ sitecode    <chr> \"MACKCC-L\", \"MACKCC-L\", \"MACKCC-L\", \"MACKCC-L\", \"MACKCC-L\"…\n$ section     <chr> \"CC\", \"CC\", \"CC\", \"CC\", \"CC\", \"CC\", \"CC\", \"CC\", \"CC\", \"CC\"…\n$ reach       <chr> \"L\", \"L\", \"L\", \"L\", \"L\", \"L\", \"L\", \"L\", \"L\", \"L\", \"L\", \"L\"…\n$ pass        <dbl> 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1…\n$ unitnum     <dbl> 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2…\n$ unittype    <chr> \"R\", \"R\", \"R\", \"R\", \"R\", \"R\", \"R\", \"R\", \"R\", \"R\", \"R\", \"R\"…\n$ vert_index  <dbl> 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 1, …\n$ pitnumber   <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…\n$ species     <chr> \"Cutthroat trout\", \"Cutthroat trout\", \"Cutthroat trout\", \"…\n$ length_1_mm <dbl> 58, 61, 89, 58, 93, 86, 107, 131, 103, 117, 100, 127, 99, …\n$ length_2_mm <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…\n$ weight_g    <dbl> 1.75, 1.95, 5.60, 2.15, 6.90, 5.90, 10.50, 20.60, 9.55, 13…\n$ clip        <chr> \"NONE\", \"NONE\", \"NONE\", \"NONE\", \"NONE\", \"NONE\", \"NONE\", \"N…\n$ sampledate  <date> 1987-10-07, 1987-10-07, 1987-10-07, 1987-10-07, 1987-10-0…\n$ notes       <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…\n```\n\n\n:::\n:::\n\n\n> **Question 1**\n>\n> List the numerical variable and the two categorical grouping variables used in this analysis.\n\n### Creating a summary table with `summarize()`\n\nBefore computing summary statistics, it is important to check whether the variables you are using contain missing values (`NA`). Summary statistics like the mean and standard deviation cannot be computed correctly if missing values are present. You can check for missing values in specific variables and remove those rows if needed. For example:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Check for missing values in the variables of interest\nand_vertebrates |> \n  summarize(\n    n_missing_length = sum(is.na(length_1_mm)),\n    n_missing_species = sum(is.na(species)),\n    n_missing_section = sum(is.na(section))\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 3\n  n_missing_length n_missing_species n_missing_section\n             <int>             <int>             <int>\n1               17                 3                 0\n```\n\n\n:::\n\n```{.r .cell-code}\n# Remove rows with missing values in these variables\nand_vertebrates_clean <-\n  and_vertebrates |> \n  filter(\n    !is.na(length_1_mm),\n    !is.na(species),\n  )\n```\n:::\n\n\n> **Question 2**\n>\n> Why is it important to check for and remove missing values *before* computing summary statistics like the mean or standard deviation?\n\nFrom this point on, we use the cleaned dataset `and_vertebrates_clean`.\n\nA summary table is a new table created from the original data in which each row represents a group and each column represents a descriptive statistic, such as a mean, standard deviation, or sample size. Instead of listing individual observations, a summary table condenses the data into a small number of values that describe key features of each group.\n\nSummary tables exist because many analyses and graphs require statistics that are not present in the raw data. Values such as means, standard errors, and uncertainty intervals must be computed before they can be plotted or interpreted. A summary table provides these computed values in an organized form that is easy to use for comparisons.\n\nRaw data contain one row per observation and preserve information about distributions, skew, and outliers. Summary tables, in contrast, contain one row per group and no longer show individual values. As a result, summary tables are useful for comparing group-level patterns, but they cannot show distribution shape. This is why raw-data plots and summary-based plots often answer different questions and are used together.\n\n> **Question 3**\n>\n> In your own words, how does a summary table differ from the raw data table?\n\nWe will now create a summary table by grouping the data by species and stream section and computing descriptive statistics for each group using `summarize()`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nand_vertebrates_summary <-\n  and_vertebrates_clean |> \n  summarize(\n    median = median(length_1_mm),\n    mean = mean(length_1_mm),\n    sd = sd(length_1_mm),\n    n = n(),\n    se = sd / sqrt(n),\n    upper_cl = mean + 2 * se,\n    lower_cl = mean - 2 * se,\n    .by = c(section, species)\n  )\n```\n:::\n\n\nThis code creates a new object called `and_vertebrates_summary`. It starts with the cleaned dataset (`and_vertebrates_clean`) and then uses `summarize()` to build a **summary table**.\n\nInside `summarize()`, each line creates a **new column** in the summary table:\n\n-   `median` and `mean` are two measures of **central tendency** for `length_1_mm`.\n-   `sd` is the **standard deviation**, which describes how spread out individual lengths are within a group.\n-   `n` is the **sample size** in that group (the number of rows contributing to the summaries).\n-   `se` is the **standard error** of the mean, computed as `sd / sqrt(n)`. This describes how precisely the group mean is estimated.\n-   `lower_cl` and `upper_cl` define a **2SE interval** around the mean: `mean ± 2 * se`. This is a rule-of-thumb interval used to describe uncertainty in the mean estimate.\n\nThe most important line for understanding how the table is built is:\n\n-   `.by = c(section, species)`\n\nThis tells R to compute all of these statistics **separately for each combination of `section` and `species`**. In the resulting table, each **row** corresponds to one `(section, species)` group, and each **column** corresponds to one statistic for that group.\n\n> **Question 4**\n>\n> What does the `.by = c(section, species)` argument do in this `summarize()` call?\n\nFinally, printing `and_vertebrates_summary` displays the completed summary table so you can inspect the group-level results.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nand_vertebrates_summary\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 9\n  section species               median  mean    sd     n    se upper_cl lower_cl\n  <chr>   <chr>                  <dbl> <dbl> <dbl> <int> <dbl>    <dbl>    <dbl>\n1 CC      Cutthroat trout         88    85.3 36.0  11072 0.342     86.0     84.6\n2 OG      Cutthroat trout         84    81.4 34.5   9356 0.356     82.1     80.7\n3 CC      Coastal giant salama…   58    60.5 20.8   5397 0.283     61.1     60.0\n4 OG      Coastal giant salama…   52    54.0 20.5   6352 0.257     54.6     53.5\n5 CC      Cascade torrent sala…   39    37    3.54     9 1.18      39.4     34.6\n6 OG      Cascade torrent sala…   34.5  34.3  7.12     6 2.91      40.1     28.5\n```\n\n\n:::\n:::\n\n\nEach row of the summary table represents one species–section combination, and the columns describe the distribution of body lengths within that group.\n\nFor Cutthroat trout, the median length is about 2.5–3 mm greater than the mean in both stream sections. This indicates left-skewed distributions, where a small number of shorter individuals pull the mean downward. Although the difference between the mean and median is modest relative to the overall variability (SD ≈ 34–36 mm), the pattern is consistent across sections.\n\nFor Coastal giant salamanders, the pattern is reversed: the mean length is about 2–2.5 mm greater than the median in both sections. This indicates right-skewed distributions, where a small number of larger individuals pull the mean upward. Notably, the *magnitude* of the mean–median difference is similar to that seen in trout, even though the direction of skew is opposite.\n\nFor Cascade torrent salamanders, sample sizes are very small (n = 6–9), and the mean and median differ by several millimeters. In this case, both measures of center are strongly influenced by individual observations, and the summaries should be interpreted cautiously.\n\n> **Question 5**\n>\n> In this dataset, is the standard error (SE) larger or smaller than the standard deviation (SD)? Why?\n\nImportantly, this summary table alone cannot show how the data are skewed, where outliers occur, or whether the distributions differ in shape. The similar mean–median differences across species could arise from very different underlying distributions. To understand those differences—and to see why the direction of skew matters—we next turn to plots of the raw data, which reveal distribution shape, spread, and outliers directly.\n\n### Question 1: How do distributions differ?\n\nIn this section, we focus on the question: How do distributions differ across groups? To answer distribution questions, we need to look at the raw data, because summary statistics alone cannot show skew, outliers, or differences in shape. Below, we use a strip (jitter) plot and a violin plot to visualize the distribution of individual body lengths in each stream section, within each species. We also overlay the group mean and median to show how measures of center can differ depending on distribution shape.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(\n  data = and_vertebrates_clean, \n  mapping = aes(x = section, y = length_1_mm)\n) +\n  geom_jitter(alpha = .2, shape = 16, width = 0.3, height = 0, size = .4) +\n  geom_violin(alpha = .5) +\n  geom_point(aes(y = mean),\n             data = and_vertebrates_summary,\n             color = \"#E69F00\", size  = 3) +\n  geom_point(aes(y = median),\n             data = and_vertebrates_summary,\n             color = \"#56B4E9\", size = 3) +\n  facet_wrap(~ species, scales = \"free_y\") +\n  labs(\n    x = \"Stream section\", \n    y = \"Body length (mm)\",\n    caption = \"CC = clearcut section, OG = old-growth section\"\n  )\n```\n\n::: {.cell-output-display}\n![](index_files/figure-typst/av-strip-plot-1.svg)\n:::\n:::\n\n\n> **Question 6**\n>\n> Name one distributional feature you can see in this plot that is *not* visible in the summary table.\n\n#### How to interpret this code\n\n-   The base `ggplot()` call uses the **raw data** (`and_vertebrates_clean`) and maps:\n\n    -   `section` to the x-axis\n    -   `length_1_mm` to the y-axis\\\n        These mappings apply to any layer that does not explicitly override them.\n\n-   `geom_jitter()` and `geom_violin()` both use the **raw data**:\n\n    -   Each point represents an individual observation\n    -   The violin shows the overall distribution shape\n    -   These layers emphasize **spread, skew, and outliers**, not just averages\n\n-   The orange and blue points use a **different dataset**, `and_vertebrates_summary`:\n\n    -   This table contains one row per species–section group\n    -   It does *not* contain individual measurements\n\n-   In `geom_point()`, the y-aesthetic is **overridden**:\n\n    -   `aes(y = mean)` plots the group mean\n    -   `aes(y = median)` plots the group median\\\n        Overriding the y-aesthetic is necessary because summary tables do not include raw values like `length_1_mm`.\n\n-   Using different datasets in different layers allows raw data and summary statistics to appear together in the same figure.\n\n-   `facet_wrap(~ species)` creates a separate panel for each species:\n\n    -   Each panel shows the same comparison across stream sections\n    -   `scales = \"free_y\"` allows each species to use its own y-axis scale\\\n        This makes distribution shape easier to see within species but prevents direct comparison of absolute values across species.\n\n-   `labs()` adds axis labels and a caption so the figure can be interpreted without additional explanation.\n\n> **Question 7**\n>\n> Why do some `geom_*()` layers use the raw dataset, while others use the summary table?\n\n> **Question 8**\n>\n> What does it mean to “override” an aesthetic inside a `geom_*()` call?\n\n#### Interpreting the distributions\n\n**Sample size**\n\n-   *Cutthroat trout* and *Coastal giant salamanders* have very large sample sizes in both stream sections.\n-   Large samples produce smooth violins and dense point clouds, allowing distribution shape to be assessed reliably.\n-   Differences in visual smoothness across panels primarily reflect **sample size**, not biological variability.\n\n**Distribution shape and modality**\n\n-   Distributions differ in shape and show evidence of **skew** and, in some cases, **multiple modes**.\n-   For trout, the distributions appear multi-modal, consistent with the presence of distinct size classes (e.g., juveniles and adults).\n-   For coastal giant salamanders, distributions are more unimodal but still skewed.\n-   Skew and modality influence how measures of center should be interpreted and whether a single “typical” value is meaningful.\n\n**Central tendency and spread**\n\n-   For trout, medians tend to be slightly higher than means, consistent with left-skewed distributions.\n-   For coastal giant salamanders, means tend to be slightly higher than medians, consistent with right-skewed distributions.\n-   The amount of variability within sections is large compared to the differences in means and medians between sections, making those differences seem small by comparison. However, even differences of only a few millimeters in body length can have important biological consequences.\n    -   Body size is often linked to **survival, growth rates, competitive ability, and reproductive success**.\n    -   As a result, small shifts in average size between stream sections could translate into meaningful differences in fitness or population dynamics.\n    -   Visualizing the full distribution helps place these mean differences in context, but it does not determine whether they are biologically important.\n\n> **Question 9**\n>\n> For this dataset, does the mean or the median better represent a “typical” individual? Briefly explain your reasoning.\n\n#### Implications for the next step in the analysis\n\n-   Because raw-data plots emphasize variability, skew, and modality, they are not ideal for clearly comparing group means when those means are close together.\n-   To focus on differences in means and their uncertainty, we need a different type of graph that does not display individual observations.\n-   In the next step, we will use a plot that emphasizes means and confidence intervals, allowing small differences between groups to be seen more clearly.\n-   The distributional patterns observed here also inform future choices about:\n    -   which summary statistics are appropriate,\n    -   whether assumptions of parametric tests are reasonable,\n    -   and which visualization best matches the specific question being asked.\n\n### Question 2: How do group means compare?\n\nIn this section, we shift focus from distribution shape to group-level averages. When the goal is to compare mean values across groups—especially when differences are small relative to overall variability—plots showing raw data can obscure those differences. Instead, we use a graph that emphasizes means and their uncertainty, allowing group means to be compared more directly while still acknowledging variation in the data.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(\n  data = and_vertebrates_summary, \n  mapping = aes(x = section)\n) +\n  geom_point(aes(y = mean),\n             color = \"#56B4E9\", size = 4, \n             position = position_nudge(x = -0.1)) +\n  geom_linerange(aes(ymin = lower_cl, ymax = upper_cl),\n                 color = \"#56B4E9\", linewidth = 1.5, \n                 position = position_nudge(x = -0.1)) +\n  geom_point(aes(y = median),\n             color = \"#E69F00\", size  = 4, \n             position = position_nudge(x = 0.1)) +\n  facet_wrap(~ species, scales = \"free_y\") +\n  labs(\n    x = \"Stream section\", \n    y = \"Body length (mm)\",\n    caption = \"CC = clearcut section, OG = old-growth section\"\n  )\n```\n\n::: {.cell-output-display}\n![](index_files/figure-typst/av-mean-plot-1.svg)\n:::\n:::\n\n\n> **Question 10**\n>\n> Why is this graph more effective than the distribution plot for comparing group means?\n\n#### How to interpret this code\n\n-   This plot uses the **summary table** (`and_vertebrates_summary`) rather than the raw data.\n    -   Each row in this dataset represents one **species–section group**\n    -   The values being plotted are **precomputed summary statistics**, not individual observations\n-   The base `ggplot()` call maps `section` to the x-axis.\n    -   No y variable is mapped globally, because different layers plot **different summary values**\n-   `geom_point(aes(y = mean))` plots the **group mean** for each stream section.\n-   `geom_linerange(aes(ymin = lower_cl, ymax = upper_cl))` draws a vertical line showing the **2SE interval** around each mean.\n    -   This layer emphasizes **uncertainty in the mean estimate**\n    -   Unlike the previous plot, raw data are not shown\n-   `geom_point(aes(y = median))` plots the **group median**.\n    -   Including the median allows direct comparison between two measures of central tendency\n-   The `position = position_nudge(x = …)` argument shifts layers **slightly left or right**:\n    -   Mean points and their 2SE intervals are nudged left\n    -   Median points are nudged right\n    -   Nudging is purely visual and prevents overlap; it does not change the data\n-   `facet_wrap(~ species)` creates a separate panel for each species.\n    -   `scales = \"free_y\"` allows each species to use its own y-axis scale\n    -   This makes mean differences within species easier to see but prevents comparison of absolute sizes across species\n-   `labs()` adds axis labels and a caption so the figure can be interpreted without additional context\n\nImportant points:\n\n-   This plot emphasizes **group means and uncertainty**, rather than distribution shape\n-   Removing raw data makes small differences in means easier to see\n-   Using summary-based plots is appropriate when the question is about **comparing averages**, not individual variability, and when the differences between summary statistics are small compared to the variability of the data.\n\n#### Interpreting group means and uncertainty\n\n**Sample size and uncertainty**\n\n-   The vertical line segments show **±2 standard errors** around each mean.\n-   For species with large sample sizes, these intervals are very narrow, indicating that the means are estimated with high precision.\n-   Where sample sizes are smaller, the 2SE intervals are wider, reflecting greater uncertainty in the mean estimates.\n\n**Means versus medians**\n\n-   The median (orange point) does not always coincide with the mean (blue point).\n-   These differences reflect skew in the underlying distributions observed in the raw-data plots.\n-   The direction of the mean–median difference differs among species, reinforcing that distribution shape affects how measures of central tendency should be interpreted.\n\n**Apparent size of differences**\n\n-   Differences between CC and OG means appear relatively large in this figure because the y-axis scale is narrow and does not show the full range of raw values.\n-   This is intentional: summary-based plots remove raw variability to make **small differences in means** easier to see.\n-   Even differences of only a few millimeters can be biologically meaningful, affecting traits such as survival, growth, or reproduction.\n\n**Why this graph type is appropriate here**\n\n-   Raw-data plots are best for understanding distribution shape and variability.\n-   Mean ± uncertainty plots are better for **comparing average values across groups** when variability would otherwise obscure those differences.\n-   Together, these plots provide complementary views of the same data and inform how group differences should be interpreted and analyzed next.\n\n### Example Results paragraph\n\n> Body length distributions differed in shape and spread among species and overlapped substantially between stream sections (Figure 1). For both Cutthroat trout and Coastal giant salamanders, body lengths showed wide distributions with clear skew, and mean and median values did not coincide, indicating asymmetric distributions.\n>\n> Despite this within-group variability, mean body length was slightly higher in clearcut (CC) sections than in old-growth (OG) sections for both species (Figure 2). For Cutthroat trout, mean body length was 85.3 mm in CC sections (approximate 95% CI: 84.6–86.0 mm) compared to 81.4 mm in OG sections (approximate 95% CI: 80.7–82.1 mm). Coastal giant salamanders showed a similar pattern, with mean body length of 60.5 mm in CC sections (approximate 95% CI: 60.0–61.1 mm) and 54.0 mm in OG sections (approximate 95% CI: 53.5–54.6 mm). Although differences in means were small relative to the full range of observed body sizes, these shifts in average body length are visible when uncertainty is summarized and raw variability is removed (Figure 2). In contrast, Cascade torrent salamanders had much smaller sample sizes, resulting in wide confidence intervals around mean body length estimates and greater uncertainty in comparisons between stream sections.\n\n-   **In-text references to figures** (Figure 1 and Figure 2)\\\n    Results should point readers to the figures that show the patterns being described, rather than restating everything shown in the plots.\n\n-   **Description of distributions** (Figure 1)\\\n    The paragraph describes spread, skew, and overlap in the raw data before discussing averages, because distribution shape affects how summary statistics should be interpreted.\n\n<!-- -->\n\n-   **Numerical reporting of group means and uncertainty** (Figure 2)\\\n    Means and approximate 95% confidence intervals are reported directly in the text so readers do not have to extract values from the figure.\n\n-   **Clear group comparisons**\\\n    Differences are described in terms of direction and approximate magnitude (CC vs. OG), without using hypothesis-testing language.\n\n<!-- -->\n\n-   **Minimal interpretation**\\\n    The paragraph reports observable patterns and places mean differences in context, but avoids causal explanations or claims about statistical significance.\n\n## Student task: Applying the workflow to bison data\n\nIn this task, you will apply the same workflow used in the worked example to a different dataset. Using the bison data, you will create summary tables, visualize distributions, and compare group means using appropriate graphs. The goal is not to explore the data freely, but to practice making deliberate choices about how to summarize, visualize, and describe data based on the question being asked.\n\n### The `knz_bison` dataset\n\nThe `knz_bison` dataset contains records of American bison sampled at Konza Prairie, including individual **body weight** measurements and **sex**. In this task, you will focus on `animal_weight` as the numerical variable of interest and `animal_sex` as the grouping variable. This dataset is smaller and simpler than the vertebrate dataset used in the worked example, making it well suited for practicing the full workflow of summarizing data, visualizing distributions, and comparing group means.\n\n### Assignment: Bison descriptive statistics and visualization\n\nUsing the `knz_bison` dataset, you will answer the **same two questions** addressed in the worked example. Follow the same workflow and make the same kinds of analytical choices, adjusting only what is necessary for the structure of this dataset.\n\n#### Step 1: Create a summary table\n\nBefore making your plots, create a summary table of `animal_weight` grouped by `animal_sex`. Your summary table should include:\n\n-   `mean`\n-   `median`\n-   `sd`\n-   `n`\n-   `se`\n-   `lower_cl` and `upper_cl` for an approximate 95% confidence interval using the 2SE rule of thumb\n\nYou will use these summary values in your plots.\n\n#### Question 1: How do distributions differ?\n\nUsing the raw bison data, create a plot that compares the distributions of body weight between sexes. Your plot should:\n\n-   Show individual observations (e.g., jitter/strip plot)\n-   Show distribution shape (e.g., a violin)\n-   Overlay the group mean and median from your summary table\n\nUse this plot to describe differences in shape, spread, and skew between groups.\n\n#### Question 2: How do group means compare?\n\nCreate a second plot that emphasizes group means and uncertainty for body weight by sex. This plot should:\n\n-   Use your summary table (not the raw data)\n-   Show the group mean and an approximate 95% confidence interval (mean ± 2SE)\n-   Optionally include the median for comparison, as in the worked example\n-   Avoid plotting individual observations\n\nUse this plot to compare group means directly, without raw-data variability obscuring differences.\n\n#### Results paragraph\n\nComplete this part of the assignment outside of class and submit it on D2L by the due date.\n\nCreate a new Microsoft Word document containing one Results-style paragraph that summarizes and compares bison body weight by sex. Your paragraph should:\n\n-   Refer explicitly to both figures you created (the distribution plot and the mean comparison plot)\n-   Describe relevant distributional features (e.g., shape, spread, skew) where they inform interpretation\n-   Report numerical values for medians.\n-   Report numerical values for means and approximate 95% confidence intervals.\n-   Briefly note whether the mean or median provides a more informative summary for bison body weight, and why.\n\nThe paragraph should read like a Results section, not a methods explanation or interpretation-heavy discussion.\n\n## Wrap-up and submission\n\nBefore leaving lab:\n\n1.  Ensure your R script is saved in your Posit Cloud project.\n\n2.  Keep your worksheet/handout for your own notes.\n\n3.  Submit **both graphs** on D2L under the *Lab 6 Graphs* assignment.\n\nAfter lab:\n\n4.   Write your Results paragraph and submit it on D2L by the posted deadline.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": null,
    "postProcess": false
  }
}