---
title: "Labs"
format:
  html:
    toc: true
    page-layout: full
---

::::::::::: {.grid .gap-3}
:::::: {.g-col-12 .g-col-sm-4}
::::: {.card .h-100}
::: card-header
Lab 1
:::

::: card-body
##### Introduction to R and RStudio {.card-title}

Introduction to R and Posit Cloud, focusing on basic calculations, functions, and understanding R’s console output.

[Lab 1](introduction-to-r-and-rstudio/)
:::
:::::
::::::

:::::: {.g-col-12 .g-col-sm-4}
::::: {.card .h-100}
::: card-header
Lab 2
:::
::: card-body
##### Workflow and Data Types {.card-title}

Working with data frames in R using the palmerpenguins dataset to practice data inspection, data types, and simple summaries.

[Lab 2](workflow-and-data-types/)
:::
::::
::::::

:::::: {.g-col-12 .g-col-sm-4}
::::: {.card .h-100}
::: card-header
Lab 3
:::
::: card-body
##### Importing Data {.card-title}

Reading external data into R, with emphasis on file structure, missing values, and correct specification of categorical variables.

[Lab 3](importing-data/)
:::
::::
::::::

:::::: {.g-col-12 .g-col-sm-4}
::::: {.card .h-100}
::: card-header
Lab 4
:::
::: card-body
##### Graphing with ggplot {.card-title}

An introduction to creating scatterplots in R using ggplot2 and a layered approach to graphing.

[Lab 4](graphing-ggplot/)
:::
::::
::::::
:::::: {.g-col-12 .g-col-sm-4}
::::: {.card .h-100}
::: card-header
Lab 5
:::
::: card-body
##### ggplot2 Visualization Challenge {.card-title}

An introduction to creating scatterplots in R using ggplot2 and a layered approach to graphing.

[Lab 5](ggplot2-vis-challenge/)
:::
::::
::::::

:::::: {.g-col-12 .g-col-sm-4}
::::: {.card .h-100}
::: card-header
Lab 6
:::
::: card-body
##### Describing Data with Summary Statistics {.card-title}

Using descriptive statistics and graphs to summarize, compare, and interpret biological data.

[Lab 6](describing-data/)
:::
::::
::::::

:::::: {.g-col-12 .g-col-sm-4}
::::: {.card .h-100}
::: card-header
Lab 7
:::
::: card-body
##### Analyzing proportions {.card-title}

Estimate population proportions, construct confidence intervals, test hypotheses about proportions, and interpret the results using biological datasets in R.

[Lab 7](analyzing-proportions/)
:::
::::
::::::

:::::: {.g-col-12 .g-col-sm-4}
::::: {.card .h-100}
::: card-header
Lab 8
:::
::: card-body
##### Transforming  Data {.card-title}

Use tidyverse tools to subset, reshape, join, and transform biological datasets into formats appropriate for analysis and visualization.

[Lab 8](transforming-data/)
:::
::::
::::::

:::::: {.g-col-12 .g-col-sm-4}
::::: {.card .h-100}
::: card-header
Lab 9
:::
::: card-body
##### Contingency Analysis {.card-title}

Analyze relationships between categorical variables using contingency tables, relative risk, odds ratios, and chi-square tests with NHANES health data.

[Lab 9](lab-09-contingency-analysis/)
:::
::::
::::::

:::::: {.g-col-12 .g-col-sm-4}
::::: {.card .h-100}
::: card-header
Lab 10
:::
::: card-body
##### t-tests {.card-title}

Compare means using one-sample, two-sample, and paired statistical tests while evaluating assumptions, selecting appropriate methods, and interpreting results in biological contexts.

[Lab 10](lab-10-t-tests/)
:::
::::
::::::

:::::: {.g-col-12 .g-col-sm-4}
::::: {.card .h-100}
::: card-header
Lab 11
:::
::: card-body
##### ANOVA {.card-title}

Compare means among multiple groups using analysis of variance, evaluate model assumptions with residual plots, and identify differences among groups using post hoc tests.

[Lab 11](lab-11-anova/)
:::
::::
::::::

:::::::::::

